### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by LiviuSo** [antoniolg/Kotlin-for-Android-Developers#28]
https://github.com/antoniolg/Kotlin-for-Android-Developers/blob/c72118e411a9462a37370c1f53a31fc63fe6748b/app/src/main/java/com/antonioleiva/weatherapp/data/db/DbDataMapper.kt#L9

Where does the id come from?

**Comment by antoniolg** [comment]
It comes from the `forecastList` that is passed to `with`:

https://github.com/antoniolg/Kotlin-for-Android-Developers/blob/678f3f381c6dc5d5176acbdb7c28916b6c1b34fd/app/src/main/java/com/antonioleiva/weatherapp/domain/model/DomainClasses.kt#L3

**Comment by LiviuSo** [comment]
Got it! My bad, sorry! Many thanks!

**Comment by Mnemoth42** [comment]
I'm in Android Studio 3.01... the program can't seem to find RecyclerView

Even copying and pasting the code from the git returns that RecyclerView cannot be found, and if you type import.android.support.v7.widget.RecyclerView, it doesn't autocomplete, nothing even close under widget... was it removed by chance?  
Oddly, adding a RecyclerView to activity_main.xml works fine...

**Comment by Mnemoth42** [comment]
Ok... anybody who gets this problem, add the following to your build gradle (the app one):
implementation 'com.android.support:recyclerview-v7:26.1.0' 
(You might have to change the version to match your current sdk).  Once I did that, it worked.  Go figure.

**Comment by antoniolg** [comment]
Yeah, to use the `recyclerview` you need to add that support library. It's explained at the beginning of chapter 5:

![image](https://user-images.githubusercontent.com/2178243/36019062-55df9c9a-0d7e-11e8-8a29-2f1141d028cf.png)

Was that your problem, or did you have to add also that line to make it work? In the past I've found myself having issues to get that library detected, solved by doing several project cleans.

**Comment by eliomaroun** [comment]
/com.example.user.weatherkotlin E/RecyclerView: No adapter attached; skipping layout
I followed your book step by step till chapter 15, and I tried to run the app on my Nexus 5.
I got an empty screen.
Can you help
Thanks in advance!!

**Comment by dakeshi** [comment]
2018년 6월 20일 (수) 오전 7:13, eliomaroun <notifications@github.com>님이 작성:

**Comment by ThaDocsN** [comment]
I followed your book to chapter 21 and I got an empty screen and this error.

W/System.err: java.util.NoSuchElementException: No element matching predicate was found.
        at com.example.weatherapp.domain.datasource.ForecastProvider.requestByZipCode(ForecastProvider.kt:31)
        at com.example.weatherapp.domain.commands.RequestForecastCommand.execute(RequestForecastCommand.kt:14)
        at com.example.weatherapp.ui.activities.MainActivity$onCreate$1.invoke(MainActivity.kt:24)
W/System.err:     at com.example.weatherapp.ui.activities.MainActivity$onCreate$1.invoke(MainActivity.kt:14)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
        at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
